In [1]:
import numpy as np

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [5]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.random.rand()

0.5493368867136533

In [11]:
np.random.rand(4,4)

array([[0.70407513, 0.87577156, 0.4419276 , 0.99544653],
       [0.93166798, 0.47887636, 0.75947885, 0.58188598],
       [0.56224749, 0.09790619, 0.53127879, 0.06874479],
       [0.82648297, 0.05425728, 0.0446753 , 0.0832737 ]])

In [12]:
np.random.randint(1,15)

14

In [13]:
np.random.randint(1,100,(10,10))

array([[15, 27, 14, 63, 48,  1,  8, 92, 35, 19],
       [55, 99, 71, 49,  3, 64, 96, 65, 60, 52],
       [ 3,  2, 36, 90, 54, 26, 31, 79, 99, 14],
       [75, 48, 65, 98, 13, 32, 57, 12,  3, 66],
       [20, 70, 68, 68, 58, 53,  3, 61, 21, 18],
       [ 6, 55, 19, 13, 67, 42, 81, 81, 97, 30],
       [32, 27, 43, 44, 78, 23, 88, 56, 67,  7],
       [41, 54, 96, 58, 10, 25, 51, 10, 16, 14],
       [ 2, 88, 67, 68, 53, 29, 25, 21, 97, 34],
       [29, 28, 87, 77,  3, 24,  1, 15, 94, 38]])