In [1]:
import numpy as np

In [5]:
arr = np.random.randint(1,10,(3,2))
print(arr)

[[6 6]
 [1 3]
 [1 6]]


In [3]:
arr.shape

(3, 2)

In [6]:
arr.reshape(1,6)

array([[6, 6, 1, 3, 1, 6]])

In [7]:
arr.reshape(2,3)

array([[6, 6, 1],
       [3, 1, 6]])

In [8]:
np.reshape(arr,(1,6))

array([[6, 6, 1, 3, 1, 6]])

In [12]:
print(arr)

[[6 6]
 [1 3]
 [1 6]]


In [10]:
np.reshape(arr,(2,3),'C')

array([[6, 6, 1],
       [3, 1, 6]])

In [11]:
np.reshape(arr,(2,3),'F')

array([[6, 1, 3],
       [1, 6, 6]])

In [13]:
np.reshape(arr,(2,3),'A')

array([[6, 6, 1],
       [3, 1, 6]])