In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1,20,10)
print(arr)

[ 1  7  2 13 19 10  7 19 12 11]


In [4]:
matriz = arr.reshape(2,5)
print(matriz)

[[ 1  7  2 13 19]
 [10  7 19 12 11]]


In [5]:
arr.max()

19

In [8]:
matriz.max(0)

array([10,  7, 19, 13, 19])

In [11]:
arr.argmax()


4


In [10]:
matriz.argmax()

4

In [12]:
arr.ptp()

18

In [13]:
matriz.ptp(0)

array([ 9,  0, 17,  1,  8])

In [16]:
np.percentile(arr, 50)

10.5

In [17]:
arr.sort()
arr

array([ 1,  2,  7,  7, 10, 11, 12, 13, 19, 19])

In [21]:
np.median(matriz, 0)

array([ 6. ,  7. , 10. , 13. , 14.5])

In [22]:
np.std(arr)

5.821511831131154

In [23]:
np.var(arr)

33.89

In [24]:
np.mean(arr)

10.1

In [31]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [34]:
b = np.expand_dims(b, axis = 0)


In [37]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])